### ISSUE TITLE
Error running ideas_dist: names of meta_ind should contain %s

### ISSUE THREAD

**Issue by ianphelps** [Sun-lab/ideas#1]
Hi, 

Thank you for creating this single cell differential expression tool. I'm trying to run ideas_dist, but running into the error mentioned in the title. Is this due to expectation of the 'var2adjust' parameter? Although this parameter is provided in your tutorial, it does not seem to be an accepted parameter of the ideas_dist function. Can you please advise as to how I should proceed?

Thanks!

My code:
```
count_matrix = as.matrix(GetAssayData(object = liver_seurat, slot = "counts"))
meta_cell = data.frame(cell_id = colnames(liver_seurat), individual = liver_seurat$sample, cell_rd_var = liver_seurat$nCount_RNA)
meta_ind = unique(data.frame(individual= liver_seurat$sample, var2test = liver_seurat$case_cntrl))
rownames(meta_ind) <- NULL

var2test      = "case_cntrl"
var2test_type = "binary" 
var_per_cell  = "cell_rd_var" #read depth variable

dist1 = ideas_dist(count_matrix, meta_cell, meta_ind, 
                   var_per_cell, var2test, 
                   var2test_type, d_metric = "Was", 
                   fit_method = "nb")
```

**Comment by mfisher1995** [comment]
Hello, I am also facing this issue. Was there a solution to this?

**Comment by liusi2019** [comment]
Hi Ian, 

First, thanks a lot for pointing out the issue of having var2adjust included in as part of the input to ideas_dist in previous version of the tutorial. Yes, var2adjust should not be part of the input to ideas_dist, and we have updated the tutorial on this. 

For the issue if having the error of "names of meta_ind should contain %s" from your code, I think the issue is, the input argument var2test expects the column name of the column in meta_ind that contains case/control labels. After the code line

```
meta_ind = unique(data.frame(individual= liver_seurat$sample, var2test = liver_seurat$case_cntrl))
```
the column name for the column containing case/control label information in the data frame meta_ind is "var2test", instead of "case_cntrl". So, 

```
var2test = "var2test"
```
should be used instead of var2test  = "case_cntrl". 

Feel free to let me know if the issue persists. 


Thanks a lot!

**Comment by liusi2019** [comment]
> Hello, I am also facing this issue. Was there a solution to this?

Hi Maggie, feel free to let me know if the previous comment to Ian's question does not solve the issue in your case. Thanks a lot!
